sonar.projectKey=jc4rlos_poke-net
sonar.projectName=PokeNet
sonar.projectVersion=1.0
sonar.organization=jc4rlos
sonar.language=csharp
sonar.dotnet.targetFramework=net8.0
sonar.sources=.
sonar.exclusions=**/bin/**,**/obj/**,**/node_modules/**,.git/**,.github/**,Properties/**
sonar.security.hotspots.reviewRatioTarget=100
